apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: telegraf
    user: telegraf
    password: metrics
    isDefault: true
    version: 1
    editable: true
    basicAuth: false
    jsonData:
      timeInterval: "5s"
